// <auto-generated />
namespace SlotCarsGo_Server.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Many2Many_laptimes_driverresults_session_track_cars : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Many2Many_laptimes_driverresults_session_track_cars));
        
        string IMigrationMetadata.Id
        {
            get { return "201803081509052_Many2Many_laptimes_driverresults_session_track_cars"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
